/**
 * @packageDocumentation
 *
 * "Why these edits" panel rendered inside the JobsPage expanded row when
 * a tailor run wrote a planner-rationale artifact (Bug E, 2026-05-25).
 *
 * @remarks
 * Lazy-fetches the JSON from `/api/tailor-runs/{id}/plan` only when the
 * user opens the panel — keeps the list view cheap for users who never
 * care about the rewrite reasoning. The component is purely presentational
 * once the data arrives; it never POSTs back to the API.
 */

import type { JSX } from "react";
import { useState } from "react";
import { useQuery } from "@tanstack/react-query";

import { fetchTailorRunPlan } from "@/lib/api/client";
import { COLOR_ON_SURFACE_VARIANT, COLOR_PRIMARY } from "@/lib/design-tokens";

/** Props for {@link TailorPlanPanel}. */
export interface TailorPlanPanelProps {
  /** Primary key of the tailor_runs row whose plan to render. */
  readonly runId: number;
}

/**
 * Render an expandable "Why these edits" panel for one tailor run.
 *
 * @param props - {@link TailorPlanPanelProps}
 * @returns Expandable panel listing per-bullet rationale plus
 *   "Kept unchanged" notes when present.
 */
export function TailorPlanPanel({ runId }: TailorPlanPanelProps): JSX.Element {
  const [open, setOpen] = useState<boolean>(false);

  const planQuery = useQuery({
    queryKey: ["tailor-run-plan", runId],
    queryFn: () => fetchTailorRunPlan(runId),
    enabled: open,
    staleTime: 60_000,
  });

  return (
    <div className="mt-3">
      <button
        type="button"
        className="text-xs font-semibold underline"
        style={{ color: COLOR_PRIMARY }}
        aria-expanded={open}
        onClick={(event) => {
          event.stopPropagation();
          setOpen((previous) => !previous);
        }}
      >
        {open ? "Hide why these edits" : "Why these edits"}
      </button>

      {open && (
        <div
          className="mt-2 rounded-xl border border-outline-variant bg-white p-3 text-xs space-y-3"
          style={{ color: COLOR_ON_SURFACE_VARIANT }}
        >
          {planQuery.isLoading && <p>Loading planner rationale…</p>}

          {planQuery.isError && (
            <p style={{ color: "#b91c1c" }}>
              Failed to load the planner artifact:{" "}
              {planQuery.error instanceof Error
                ? planQuery.error.message
                : "unknown error"}
              .
            </p>
          )}

          {planQuery.data && (
            <>
              <div>
                <p className="text-[10px] uppercase tracking-widest font-bold text-outline">
                  Overall plan
                </p>
                <p className="mt-1 whitespace-pre-line">
                  {planQuery.data.plan.rewrite_plan}
                </p>
              </div>

              <div>
                <p className="text-[10px] uppercase tracking-widest font-bold text-outline">
                  Per-bullet decisions ({planQuery.data.plan.bullets.length})
                </p>
                <ul className="mt-1 space-y-2">
                  {planQuery.data.plan.bullets.map((bullet) => (
                    <li
                      key={bullet.id}
                      className="rounded-lg border border-outline-variant/40 p-2"
                    >
                      <p className="font-semibold">
                        {bullet.id}{" "}
                        <span className="text-outline">
                          ({bullet.action})
                        </span>
                      </p>
                      <p className="italic mt-0.5">{bullet.rationale}</p>
                      {bullet.action === "rewrite" && bullet.new_text && (
                        <p className="mt-1">
                          <span className="font-semibold">New:</span>{" "}
                          {bullet.new_text}
                        </p>
                      )}
                    </li>
                  ))}
                </ul>
              </div>

              {planQuery.data.plan.kept_unchanged.length > 0 && (
                <div>
                  <p className="text-[10px] uppercase tracking-widest font-bold text-outline">
                    Kept unchanged ({planQuery.data.plan.kept_unchanged.length})
                  </p>
                  <ul className="mt-1 space-y-1">
                    {planQuery.data.plan.kept_unchanged.map((note) => (
                      <li key={note.id}>
                        <span className="font-semibold">{note.id}:</span>{" "}
                        {note.reason}
                      </li>
                    ))}
                  </ul>
                </div>
              )}

              <p className="text-[10px] text-outline">
                Generated by {planQuery.data.plan.model} ·{" "}
                {planQuery.data.plan.saved_at}
              </p>
            </>
          )}
        </div>
      )}
    </div>
  );
}
