"""Core types and protocol for the AI provider abstraction.

The unified abstraction kept its name even after Codex / Anthropic /
Gemini providers were removed in the post-issue-61 cleanup, so the gate
/ tailor / review / apply stages can continue depending on the
`AIProvider` protocol rather than importing the OpenAI SDK directly.

Cost-aware additions (issue #59):
    `TokenUsage` and `CostBreakdown` carry per-call accounting that
    providers compute themselves so the central recorder can stay
    pricing-agnostic. Each provider owns its cache-discount math
    (OpenAI 50% on cached input, Anthropic 10% on cache-read, etc.)
    and emits an authoritative `CostBreakdown` for persistence.
"""

from __future__ import annotations

from enum import Enum
from typing import Literal, Protocol, runtime_checkable

from pydantic import BaseModel, Field


class ProviderMode(str, Enum):
    """How the user authenticates with the AI backend.

    BYOK: User supplies their own API key for the configured provider.
    """

    BYOK = "byok"


class ProviderType(str, Enum):
    """Supported AI provider backends.

    Each value maps to a concrete AIProvider implementation.
    """

    OPENAI = "openai"
    OPENROUTER = "openrouter"


class CompletionMessage(BaseModel):
    """A single message in a chat completion exchange.

    Attributes:
        role: Message author role (system, user, assistant).
        content: Text content of the message.
    """

    role: str
    content: str


class CompletionRequest(BaseModel):
    """Provider-agnostic request for a chat completion.

    Attributes:
        messages: Ordered list of conversation messages.
        model: Optional model override (provider uses its default if omitted).
        temperature: Sampling temperature. Lower values are more deterministic.
        max_tokens: Maximum tokens in the completion response.
        response_format: Optional response format hint (e.g. "json").
    """

    messages: list[CompletionMessage]
    model: str | None = None
    temperature: float = Field(default=0.3, ge=0.0, le=2.0)
    max_tokens: int = Field(default=4096, gt=0)
    response_format: str | None = None


class TokenUsage(BaseModel):
    """Per-call token accounting captured from the provider response.

    Attributes:
        prompt_tokens: Total prompt tokens consumed (includes cached).
        completion_tokens: Completion tokens generated by the model.
        cached_input_tokens: Subset of `prompt_tokens` served from cache.
        reasoning_tokens: Subset of `completion_tokens` spent on hidden
            reasoning (gpt-5.x families). Zero for non-reasoning models.
    """

    prompt_tokens: int = Field(default=0, ge=0)
    completion_tokens: int = Field(default=0, ge=0)
    cached_input_tokens: int = Field(default=0, ge=0)
    reasoning_tokens: int = Field(default=0, ge=0)


CostSource = Literal["provider", "computed", "unknown"]


class CostBreakdown(BaseModel):
    """USD cost components for one LLM call.

    Attributes:
        input_cost_usd: Cost attributed to billable prompt tokens.
        output_cost_usd: Cost attributed to completion tokens.
        cached_input_cost_usd: Cost attributed to cached prompt tokens
            (already discounted; not double-counted with `input_cost_usd`).
        total_cost_usd: Sum the central recorder should persist.
        source: Whether the value was provider-reported, locally computed,
            or unavailable.
    """

    input_cost_usd: float = Field(default=0.0, ge=0.0)
    output_cost_usd: float = Field(default=0.0, ge=0.0)
    cached_input_cost_usd: float = Field(default=0.0, ge=0.0)
    total_cost_usd: float = Field(default=0.0, ge=0.0)
    source: CostSource = "unknown"


class CompletionResponse(BaseModel):
    """Provider-agnostic response from a chat completion.

    Attributes:
        content: The generated text content.
        model: The model that produced this response.
        provider: The provider backend that handled the request.
        usage: Per-call token accounting (replaces flat
            `usage_prompt_tokens` / `usage_completion_tokens`).
        cost: USD breakdown computed by the provider; central recorder
            persists `cost.total_cost_usd` without re-pricing.
        raw_response: Optional raw response payload for debugging.
    """

    content: str
    model: str
    provider: str
    usage: TokenUsage = Field(default_factory=TokenUsage)
    cost: CostBreakdown = Field(default_factory=CostBreakdown)
    raw_response: dict[str, object] | None = None


class ProviderConfig(BaseModel):
    """Persisted configuration for the active AI provider.

    Attributes:
        mode: Whether the user is using Codex OAuth or BYOK.
        provider_type: Which backend to route requests to.
        api_key: Encrypted API key for BYOK mode. None for Codex.
        base_url: Optional custom endpoint URL (for OpenRouter, Ollama, etc.).
        default_model: Optional default model to use when requests omit one.
        codex_home_path: Directory where Codex stores auth tokens.
    """

    mode: ProviderMode
    provider_type: ProviderType
    api_key: str | None = None
    base_url: str | None = None
    default_model: str | None = None
    codex_home_path: str | None = None


@runtime_checkable
class AIProvider(Protocol):
    """Contract that all AI provider implementations must satisfy.

    Providers handle authentication, request formatting, response
    parsing, AND cost computation for a specific backend (OpenAI,
    OpenRouter, ...). Centralizing cost on the provider keeps the
    recorder pricing-agnostic and lets each provider own its
    cache-discount math.
    """

    @property
    def provider_type(self) -> ProviderType:
        """Return the provider backend type."""
        ...

    @property
    def is_authenticated(self) -> bool:
        """Return True if the provider has valid credentials."""
        ...

    async def complete(self, request: CompletionRequest) -> CompletionResponse:
        """Send a chat completion request and return the response.

        Args:
            request: Provider-agnostic completion request.

        Returns:
            A normalized completion response carrying `usage` and `cost`.

        Raises:
            ProviderAuthError: If credentials are missing or expired.
            ProviderRateLimitError: If the provider rate-limits the request.
            ProviderError: For all other provider failures.
        """
        ...

    def compute_cost(self, model: str, usage: TokenUsage) -> CostBreakdown:
        """Compute USD cost for a token-usage triple under one model.

        Purpose:
            Centralize per-provider pricing so the recorder never needs
            to know about cache discounts or reasoning surcharges.
        Args:
            model: Fully qualified or provider-bare model identifier.
            usage: Token counts captured from the raw completion.
        Returns:
            A populated `CostBreakdown`. Implementations return
            `CostBreakdown(source="unknown")` when pricing for the
            given model is not available.
        """
        ...

    async def validate_credentials(self) -> bool:
        """Test whether the current credentials are valid.

        Makes a minimal API call to verify the key/session works.

        Returns:
            True if credentials are valid, False otherwise.
        """
        ...
